### ISSUE TITLE
please use a branch name corresponding to an assignment

### ISSUE THREAD

**Issue by ritjoe** [CalvinWu4/hfoss#2]
As per 

https://github.com/ritjoe/hfoss/wiki/grading-policies

your pull requests should be submitted from feature branches whose names match the assignment name and corresponding key in your YAML file.

See, for example, 

http://hfoss.rocfoss.org/participants/

for the form of these assignment names.

**Comment by ritjoe** [comment]
So, this means blog04, blog05 (which is still missing even from your fork), meetup1 (please note the lack of an initial zero (0) because there should be <<10 meetups total), and bugfix, which are all past due. Should I create an issue for each of them? 

Feel free to reply to this issue, or to email me privately if you need help effecting these submissions.

**Comment by CalvinWu4** [comment]
they should be pushed now
what do you mean by "please note the lack of an initial zero (0) because there should be <<10 meetups total"
